Packageretrieve
coveo/vsforce pull request #47
Opened 2016-10-05 17:36 UTC by erocheleau

Retrieve the unpackaged files described in the package.xml selected by the user at the moment of retrieve. Unzips the result of the retrieve command in the same folder where you selected the package.xml file.

To test this, simply run the extension in a folder where you have a package.xml somewhere describing metadata objects you have in your connected org and it should ask you to choose your package.xml if you have more than one, otherwise it will take the only one it finds.
It should created the folder structure related to the objects you have in your package.xml and then unzip those files in the proper folders.

This looks like a lot of changes because of the linting of files at the same time.

[x] Code is up-to-date with the `master` branch

2016-10-05 18:20 UTC, lbenie approved these changes

2016-10-05 18:23 UTC, tedre191 requested changes

2016-10-05 18:48 UTC, erocheleau commented on package.json
> +                "command": "extension.sfdeploy",
I did not do dis

2016-10-05 19:08 UTC, erocheleau commented on src/commands/retrieveCommand.ts
> +	 */
Should be fixed, dont know how to mark this as resolved...

2016-10-05 19:08 UTC, erocheleau commented on src/commands/retrieveCommand.ts
> +	 */
Should be fixed, dont know how to mark this as resolved...

2016-10-06 12:06 UTC, lbenie commented on package.json
> +                "command": "extension.sfdeploy",
my fault 😢  hehe bad copy paste 😈

2016-10-07 17:21 UTC, erocheleau commented
:worksonmymachine:
🚀 

Same Travis error as before even if I merged master into my branch.

`error: unable to create symlink tslint.json (File name too long)`

2016-10-07 17:25 UTC, lbenie commented
Hmm that issue has been resolved...

imo just merge it and it should be fine

2016-10-13 17:19 UTC, tedre191 approved these changes

2016-10-13 17:19 UTC, merged