PR for release
coveo/vsforce pull request #92
Opened 2016-10-27 21:45 UTC by erocheleau

Main features:
- The deploy package command now handles correctly the partial successes/failures.
- The deploy errors will be displayed using vscode Diagnostic feature.

Minor stuff:
- Added examples of tests to run on build.
- Configured Travis to run the tests on a new PR both in develop and master.

2016-10-27 21:53 UTC, lbenie approved these changes
so much rebase

2016-10-28 14:59 UTC, tedre191 approved these changes

2016-10-28 14:59 UTC, tedre191 commented on .travis.yml
> +  - if [ $TRAVIS_OS_NAME == "linux" ]; then
lol ?

2016-10-28 14:59 UTC, tedre191 commented on .travis.yml
> +  - npm run vscode:prepublish
ça va dans script

2016-10-28 15:10 UTC, lbenie commented on .travis.yml
> +  - if [ $TRAVIS_OS_NAME == "linux" ]; then
on spawn 2 machines maintenant linux/osx
ca vient d'un exemple de microsoft IIRC

2016-10-28 15:12 UTC, erocheleau commented on .travis.yml
> +  - npm run vscode:prepublish
non je l'ai change selon l'exemple de vscode non?

2016-10-28 15:14 UTC, erocheleau commented on .travis.yml
> +  - osx
We should really remove the osx, since it puts our build in a queue to wait for an available osx machine and it takes about 30 minutes :(

2016-10-28 15:14 UTC, erocheleau commented on .travis.yml
> +  - npm run vscode:prepublish
Il est effectivement dans scripts...

2016-10-28 15:15 UTC, lbenie commented on .travis.yml
> +  - osx
yep let's do it

2016-10-28 19:14 UTC, lbenie requested changes
by default it should be set to ''

check package.json

🙉

2016-10-28 21:13 UTC, tedre191 requested changes

2016-10-28 21:13 UTC, tedre191 commented on package.json
> +                    "default": "",
Nope. validation will fail if we passe "" as default for required configs

2016-10-28 21:13 UTC, tedre191 commented on package.json
> +                    "default": "",
same

2016-10-29 02:40 UTC, erocheleau commented on package.json
> +                    "default": "",
Can't we check on length > 0 instead?

2016-10-29 02:40 UTC, erocheleau commented on package.json
> +                    "default": "",
Can't we check on length > 0 instead?

2016-10-29 02:40 UTC, erocheleau commented on package.json
> +                    "default": "",
null is definitely not an expected value for a string...

2016-10-29 02:42 UTC, tedre191 commented on package.json
> +                    "default": "",
we could, either way works

2016-10-31 15:08 UTC, lbenie approved these changes

2016-10-31 20:22 UTC, tedre191 approved these changes
:shipit:

2016-10-31 21:24 UTC, merged